### ISSUE TITLE
有没有考虑到多环境请求代理

### ISSUE THREAD

**Issue by chengnuo** [kimjuny/koa-react-universal#11]
比如:
www.a.com
www.b.com
www.c.com
....
koa-webpack-server 只是环境配置。并没有代理

**Comment by kimjuny** [comment]
Hi，你所指的代理是[webpack-dev-server](https://github.com/webpack/webpack-dev-server)这种可以用来跨域的代理吗？考虑到我们已经在使用node服务器了，所以代理应该走这台服务器，除非你有特殊需求需要请求外部代理。至于多环境，你可以通过webpack的definePlugin设置环境变量，自己实现多环境的代理路由映射。

**Comment by chengnuo** [comment]
谢谢回答解惑 我说的是跨域代理。

**Comment by kimjuny** [comment]
@chengnuo 好的，有什么其他问题可以提Issue
