### ISSUE TITLE
bootstrap

### ISSUE THREAD

**Issue by zhaofang** [kimjuny/koa-react-universal#45]
new webpack.optimize.CommonsChunkPlugin({
      names: ['bootstrap'], // needed to put webpack bootstrap code before chunks.
      filename: '[name].[chunkhash].js',
      minChunks: Infinity
    }),

why use bootstrap?

**Comment by kimjuny** [comment]
I'm not getting your point.
Are you referring this "bootstrap" as THE "[bootstrap](https://github.com/twbs/bootstrap)"?
