### ISSUE TITLE
update React and React-dom to V16.8.6  Hooks cannot work

### ISSUE THREAD

**Issue by wlc534** [kimjuny/koa-react-universal#57]
update React and React-dom to V16.8.6  Hooks cannot work
"react": "^16.8.6",
"react-dom": "^16.8.6",

import React, { useState } from 'react';

export  default  function Example() {
  // Declare a new state variable, which we'll call "count"
  const [count, setCount] = useState(0);

  return (
    <div>
      <p>You clicked {count} times</p>
      <button onClick={() => setCount(count + 1)}>
        Click me
      </button>
    </div>
  );
}

**Comment by kimjuny** [comment]
done
